---
output:
  word_document: default
  github_document: default
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  error = FALSE,
  message = FALSE,
  warning = FALSE
)
```

# Análise Doutorado Débora

## Biorigin

### Carregando pacotes
```{r}
library(tidyverse)
library(ExpDes.pt)
library(lme4)
library(agricolae)
library(readxl)
library(janitor)
library(MASS)
library(car)
```

### Entrada de dados
```{r}
## Lendo os dados
dados <- read_xlsx("data/dados_01.xlsx",
          sheet = "Análises Fezes",
          na=".") %>% 
  clean_names() %>% 
  mutate(
    dose = case_when(
      tr == 1 ~ 0,
      tr == 2 | tr == 5 ~ 0.2,
      tr == 3 | tr == 6 ~ 0.4,
      tr == 4 | tr == 7 ~ 0.8
    ),
    ingrediente = ifelse(tr==1,"PCL",
                         ifelse(tr > 1 & tr<=4 ,"PCL","PCLs")),
    
    # transformação dos dados
    # mo = log(mo),
    # fibra_in = log(fibra_in),
    # ee_in = log(ee_in),
    # amido_in = log(amido_in),
    # ph=ph^(-2),
    # am=am^2
  )

#extraindo o controle
da <- dados %>% filter(dose==0) %>% 
  mutate(
    ingrediente="PCLs"
  )

#duplicando o controle
dados <- rbind(dados,da)
```


### Vislumbre
```{r}
# glimpse(dados)
```
## Normalidade de Homocedasticidade

```{r}
variaveis <- dados %>% 
  dplyr::select(mm:tripta_63,-score)

for(i in seq_along(variaveis)){
  nome <- names(variaveis[i])
  print("====================================")
  print(str_to_upper(nome))
  print("====================================")

  daux <- variaveis[i]
  names(daux) <- "y" ### <-
  
  y <- daux$y ### <-
  daux$bl <- dados$bl %>% as_factor()
  daux$tr <- dados$tr %>% as_factor()
  
  daux <- daux %>%  drop_na()
  y <- daux$y ### <-
  bl <- daux$bl %>% as_factor()
  tr <- daux$tr %>% as_factor()
  
  mod <- aov(y ~ tr + bl)
  rs <- mod %>% rstudent()
  hist(rs, main = paste("Resíduo ", str_to_upper(nome)) )

  print(shapiro.test(rs))

  plot(y ~ tr)
  cat("Médias por tratamentos\n")
  medias <- data.frame(y, tr) %>% 
    group_by(tr) %>% 
    summarise(media = mean(y,na.rm=TRUE))
    print(medias)

  filtro <- y != 0
  mod_box <- aov(y[filtro] ~ tr[filtro] + bl[filtro])
  boxcox(mod_box,seq(-10,10,.5))
  abline(v=1,col="red",lty=2)
  
  preditos <- predict(mod)
  plot(preditos,rs,
       main=paste("Estudos de Outliers: ", str_to_upper(nome)))
  
  dfa <- data.frame(Trat = tr, Bloco = bl, Y = y, Pred = preditos, RS =rs) %>% 
    filter(RS >= 3 | RS <= -3) %>% 
    dplyr::select(Trat, Bloco, Y)
  
  cat("Outliers")
  print(dfa)
  abline(h=c(3,-3),col="red")
  cat("\n")
}
```



## Análise de variância

```{r}
# for(i in seq_along(variaveis)){
#   nome <- names(variaveis[i])
#   print("====================================")
#   print(str_to_upper(nome))
#   print("====================================")
#   
#   daux <- variaveis[i]
#   names(daux) <- "y" ### <-
#   y <- daux$y ### <- 
#   ingred <- dados$ingrediente %>% as_factor()
#   dose <- dados$dose
#   bl <- dados$bl %>% as_factor()
#   
#   fat2.dbc(ingred,dose,bl,y,quali=c(TRUE,FALSE),
#            fac.names = c("Ingred.","Dose"))
#   
#   my_plot<-tibble(dose,ingred,y) %>%
#     group_by(dose,ingred) %>% 
#     summarise(y=mean(y)) %>% 
#     ggplot(aes(x=dose,y=y,color=ingred)) +
#     geom_point(size=3) +
#     geom_line() +
#     #facet_wrap(~ingred,nrow = 2)+
#     theme_bw() +
#     labs(y=str_to_upper(nome),x="DOSE",color="Ingrediente")+
#     theme(legend.position = "top")+
#     scale_color_manual(values = c("aquamarine4","red")) 
#   print(my_plot)
#   cat("\n")
# }
```







